FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY BankAccoutFrontEnd/bankBackend/pom.xml .
COPY BankAccoutFrontEnd/bankBackend/src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/bankBackend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]